version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/shared/apps/docker/homepage/config/:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000